CREATE TABLE [dbo].[Books]
(
	[ISBN] NVARCHAR (50) NOT NULL,
	[BookTitle] NVARCHAR(100) NOT NULL,
	[YearPublished] INT NOT NULL,
	[AuthorID] INT NOT NULL,
	CONSTRAINT PK_BOOKS PRIMARY KEY (ISBN),
	CONSTRAINT FK_AUTHORS_BOOKS FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID)
)
