CREATE TABLE [dbo].[Loans]
(
	[StudentID] NVARCHAR(9) NOT NULL,
	[ISBN] NVARCHAR (50) NOT NULL,
	[DateBorrowed] DATE NOT NULL,
	CONSTRAINT PK_LOANS PRIMARY KEY (StudentID, ISBN, DateBorrowed),
	CONSTRAINT FK_LOANS_STUDENTS FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
	CONSTRAINT FK_LOANS_BOOKS FOREIGN KEY (ISBN) REFERENCES Books(ISBN)
)
